# Versión de la sintaxis de Docker Compose. '3.8' es una versión moderna y estable.
version: '3.8'

services:
  # Servicio Frontend (Apache)
  apache-server:
    image: httpd:2.4          # Usamos la imagen oficial de Apache httpd, versión 2.4.
    container_name: mi_servidor_apache # Un nombre amigable para el contenedor.
    ports:
      - "8080:80"             # Mapea el puerto 8080 de tu máquina al puerto 80 del contenedor.
    volumes:
      - ./src:/usr/local/apache2/htdocs/
    depends_on:
      - backend-api # Le dice a Docker que inicie el backend antes que el frontend

  # Servicio Backend (API de Python)
  backend-api:
    build: ./backend          # Le dice a Docker que construya la imagen desde el Dockerfile en la carpeta ./backend
    container_name: mi_api_python
    ports:
      - "5001:5000"           # Mapea el puerto 5001 de tu máquina al 5000 del contenedor (donde corre Flask)
    volumes:
      - ./backend:/app        # Monta el código del backend para reflejar cambios al instante
